NBProject/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entities;
using Domain;
using NBProject.Models;

namespace NBProject.Controllers
{
    public class CartController : Controller
    {

        public ViewResult Index(string returnUrl)
        {
            return View(new KorpaViewModel
            {
               
                Cart = new Cart(),
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(string Name, string returnUrl)
        {
            Cart newCart = new Cart();
            Song toCart = DataProvider.getSongByName(Name);
            newCart.AddItem(toCart);
            return RedirectToAction("List", "Song");
            
        }
        public RedirectToRouteResult RemoveFromCart(string Name, string returnUrl)
        {
            Cart newCart = new Cart();
            Song toCart = DataProvider.getSongByName(Name);
            newCart.RemoveLine(toCart);
          
            return RedirectToAction("Index", new { returnUrl });
            
        }
        //private Cart GetCart()
        //{
        //    Cart cart = (Cart)Session["Cart"];
        //    if (cart == null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}


        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            Cart newChart = new Cart();
            newChart.removeAll();
            return View();
        }
    }
}

NBProject/Controllers/NavController.cs
using Domain;
using Domain.Entities;
using NBProject.Models;
using Newtonsoft.Json;
using RedisDataLayer;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NBProject.Controllers
{
    public class NavController : Controller
    {

        public PartialViewResult Menu(string category = null,string singerSelected = null)
        {

            ViewBag.SelectedCategory = category;
            ViewBag.SingerSelected = singerSelected;

            List<string> kategorije = DataProvider.getAllCategories();
            List<Singer> pevaci = DataProvider.getAllSingers();

            NavModelView newModel = new NavModelView(kategorije.Distinct().ToList(), pevaci);
            return PartialView(newModel);
        }

        public PartialViewResult Profile(string id = null)
        {
            ProfilViewModel model = new ProfilViewModel();
            if (id != null)
            {
                Song songProf = DataProvider.getSongByName(id);
                Singer singerProf = DataProvider.getSingerBySongName(id);
                //Singer singerProf = DataProvider.getSingerByName(songProf.Singer);
                model.singerAlias = singerProf.Alias;
                model.singerBirthYear = singerProf.YearOfBirth;
                model.singerName = singerProf.Name;
                model.concNameAndAlias = model.singerName + model.singerAlias;
                model.songLyrics = songProf.Lyrics;
                model.songName = songProf.Name;
            }

            return PartialView(model);
        }

        public ActionResult GetImage(string concNameAndAlias)
        {
            //Vraca sliku pevaca na osnovu njegovog ida
            if (concNameAndAlias != null)

            {
                if (!DatabaseManager.Exists(concNameAndAlias))
                {
                    Data picture = DataProvider.GetDataByName(concNameAndAlias).FirstOrDefault();
                    if (picture != null)
                    {
                        string singer = JsonConvert.SerializeObject(picture);
                        DatabaseManager.StoreData(concNameAndAlias, singer);
                        return File(picture.Media, picture.Mime);

                    }
                    else
                    {

                        var dir = Server.MapPath("/Content/");
                        var path = Path.Combine(dir, "MusicStore.jpg");
                        return base.File(path, "image/jpeg");
                    }
                }
                else
                {
                    string singer = DatabaseManager.GetData(concNameAndAlias);
                    Data picture = JsonConvert.DeserializeObject<Data>(singer);
                    return File(picture.Media, picture.Mime);
                }
            }
            else
            {
                var dir = Server.MapPath("/Content/");
                var path = Path.Combine(dir, "MusicStore.jpg");
                return base.File(path, "image/jpeg");
            }
        }
    }
}

NBProject/Views/Shared/_CRUDlayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

NBProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="~/Scripts/jquery-3.2.1.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />

    <title>MusicStore</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="">Music Store</a>
        @Html.RouteLink("SongCRUD", new
        {
         controller = "CRUD",
         action = "Index",
     }, new
     {
         @class = "navbar-brand"
     })


        @Html.RouteLink("SingerCRUD", new
     {
         controller = "CRUD",
         action = "IndexSinger",
     }, new
     {
         @class = "navbar-brand"
     })    

     @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-2">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-7 bg-dark" >
            @RenderBody()
        </div>
        <div id="SingerInfo" class="col-xs-3">
            @Html.Action("Profile", "Nav")
          
        </div>

    </div>
 </body>
</html>